# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a1dacc86627a626d73b6583e7702b2f013a466be56b0c8d01f2c08a0a2529696980694895dba5dbcbfc05da2367e645b74b6fe9661f656aebcccca25759fec9

test:
  secret_key_base: b198116b2dbbcf7e82360a2f0e854de553c12de9dffb197eb36481f5fb96f8b7324c69e1104c604df23c0afb248f965725df435ddf3704b44c348cfaaacb1ca0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
